worker_processes 1;

events { worker_connections 1024; }

http {

    sendfile on;

    upstream docker-client {
        server client:3000;
    }

    upstream docker-pocketbase {
        server pocketbase:8080;
    }

    server {
        listen [::]:443 ssl;
        listen 443 ssl;
        server_name gg.bearbyte.org;
        ssl_certificate /etc/letsencrypt/live/app.golfgeek.io/fullchain.pem; # managed by Certbot
        ssl_certificate_key /etc/letsencrypt/live/app.golfgeek.io/privkey.pem; # managed by Certbot
        include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

        location / {
            proxy_pass         http://docker-client;
            proxy_redirect     off;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Host $server_name;
        }

        location /pb/_/ {
            proxy_pass         http://docker-pocketbase/_/;
            proxy_redirect     off;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Host $server_name;
        }

        location /pb/api/ {
            proxy_pass         http://docker-pocketbase/api/;
            proxy_redirect     off;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Host $server_name;
        }
    }

    server {
        listen 80;
        server_name gg.bearbyte.org;
        return 301 https://$host$request_uri;
    }
}
